### ISSUE TITLE
Decorator on the endpoint

### ISSUE THREAD

**Issue by devamin** [KiraPC/fastapi-router-controller#25]
It would be good if we can add a decorator to the endpoint something like this :
```
@controller.route.get("/{id}", status_code=status.HTTP_200_OK, response_model=UserModelSchemaRes)
    @authenticated(Depends(oauth2_scheme))
    def get_user(self, id: int):
        """Get One User By id."""
```

but the controller parser bug with the following : 
```
Traceback (most recent call last):
  File "/Users/aaaa/.pyenv/versions/3.9.10/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/aaaa/.pyenv/versions/3.9.10/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/aaa/pypoetry/virtualenvs/api-q8MsJZi5-py3.9/lib/python3.9/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/Users/aaa/pypoetry/virtualenvs/api-q8MsJZi5-py3.9/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/Users/aaaa/.pyenv/versions/3.9.10/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/Users/aaa/pypoetry/virtualenvs/api-q8MsJZi5-py3.9/lib/python3.9/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/Users/aaa/pypoetry/virtualenvs/api-q8MsJZi5-py3.9/lib/python3.9/site-packages/uvicorn/config.py", line 479, in load
    self.loaded_app = import_from_string(self.app)
  File "/Users/aaa/pypoetry/virtualenvs/api-q8MsJZi5-py3.9/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/Users/aaaa/.pyenv/versions/3.9.10/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Volumes/fs/code/project./web/app.py", line 12, in <module>
    from web.apps.auth.app import auth_app
  File "/Volumes/fs/code/project./web/apps/auth/app.py", line 6, in <module>
    auth_app = create_app(controllers)
  File "/Volumes/fs/code/project./web/app_factory.py", line 19, in create_app
    app.include_router(controller.router())
  File "/Users/aaa/pypoetry/virtualenvs/api-q8MsJZi5-py3.9/lib/python3.9/site-packages/fastapi_router_controller/lib/controller.py", line 98, in <lambda>
    cls.router = lambda: Controller.__parse_controller_router(cls)
  File "/Users/aaa/pypoetry/virtualenvs/api-q8MsJZi5-py3.9/lib/python3.9/site-packages/fastapi_router_controller/lib/controller.py", line 148, in __parse_controller_router
    signature_parameters[0] = signature_parameters[0].replace(
  File "/Users/aaaa/.pyenv/versions/3.9.10/lib/python3.9/inspect.py", line 2580, in replace
    return type(self)(name, kind, default=default, annotation=annotation)
  File "/Users/aaaa/.pyenv/versions/3.9.10/lib/python3.9/inspect.py", line 2507, in __init__
    raise ValueError(msg)
ValueError: variadic positional parameters cannot have default values
```

**Comment by KiraPC** [comment]
Hi @devamin

Yes, this could be a great feature, but I think it is far away from the purpose of this library.

This library is designed to allow the usage of FastaAPI router inside Python Classes and not to extends FastaAPI functionalities. 

You could ask this feature in the [FastAPI](https://github.com/tiangolo/fastapi) repository.

;)

**Comment by devamin** [comment]
No it's up to the controller lib, because I created that decorator all good, but the controller parser bug with the following : 
```
Traceback (most recent call last):
  File "/Users/bkamine/.pyenv/versions/3.9.10/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/bkamine/.pyenv/versions/3.9.10/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/bkamine/Library/Caches/pypoetry/virtualenvs/metin-api-q8MsJZi5-py3.9/lib/python3.9/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/Users/bkamine/Library/Caches/pypoetry/virtualenvs/metin-api-q8MsJZi5-py3.9/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/Users/bkamine/.pyenv/versions/3.9.10/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/Users/bkamine/Library/Caches/pypoetry/virtualenvs/metin-api-q8MsJZi5-py3.9/lib/python3.9/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/Users/bkamine/Library/Caches/pypoetry/virtualenvs/metin-api-q8MsJZi5-py3.9/lib/python3.9/site-packages/uvicorn/config.py", line 479, in load
    self.loaded_app = import_from_string(self.app)
  File "/Users/bkamine/Library/Caches/pypoetry/virtualenvs/metin-api-q8MsJZi5-py3.9/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/Users/bkamine/.pyenv/versions/3.9.10/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Volumes/fs/code/pro/partner/partner-backend/./web/app.py", line 12, in <module>
    from web.apps.auth.app import auth_app
  File "/Volumes/fs/code/pro/partner/partner-backend/./web/apps/auth/app.py", line 6, in <module>
    auth_app = create_app(controllers)
  File "/Volumes/fs/code/pro/partner/partner-backend/./web/app_factory.py", line 19, in create_app
    app.include_router(controller.router())
  File "/Users/bkamine/Library/Caches/pypoetry/virtualenvs/metin-api-q8MsJZi5-py3.9/lib/python3.9/site-packages/fastapi_router_controller/lib/controller.py", line 98, in <lambda>
    cls.router = lambda: Controller.__parse_controller_router(cls)
  File "/Users/bkamine/Library/Caches/pypoetry/virtualenvs/metin-api-q8MsJZi5-py3.9/lib/python3.9/site-packages/fastapi_router_controller/lib/controller.py", line 148, in __parse_controller_router
    signature_parameters[0] = signature_parameters[0].replace(
  File "/Users/bkamine/.pyenv/versions/3.9.10/lib/python3.9/inspect.py", line 2580, in replace
    return type(self)(name, kind, default=default, annotation=annotation)
  File "/Users/bkamine/.pyenv/versions/3.9.10/lib/python3.9/inspect.py", line 2507, in __init__
    raise ValueError(msg)
ValueError: variadic positional parameters cannot have default values
```

**Comment by devamin** [comment]
You can reproduce this by adding any decorator to the endpoint.

**Comment by KiraPC** [comment]
@devamin Oh, ok. Now I can understand better. It is a library bug.

I'll try to fix it ASAP.

**Comment by devamin** [comment]
@KiraPC I figure it out, it's not an issue in the lib, basically the wrapper need `@wrap` to get inspected. Sorry for the bother ;).

**Comment by KiraPC** [comment]
Oh, perfect. Let me close the issue.
